pipeline:
  build_dry_run:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: publicintegrity/fec-loader
    tags:
      - ${DRONE_COMMIT_SHA:0:12}
      - latest
    dry_run: true
    when:
      event: [push, tag]

  build_push:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: publicintegrity/fec-loader
    tags:
      - ${DRONE_COMMIT_SHA:0:12}
      - latest
    when:
      event: deployment
      environment: production

  pipeline_update:
    image: laurentgoderre/pachctl:1.8.3-alpine
    environment:
      - PACHD_ADDRESS=pachd.pachyderm.svc.cluster.local:650
      - IMAGE_TAG=${DRONE_COMMIT_SHA:0:12}
    commands:
      # temp proof of concept, should build docker file including this stuff
      - apk --update add nodejs nodejs-npm jq && rm -rf /var/cache/apk/*
      - npm install -g yamlxjson
      - for file in $(find ./pipelines -name "*.yml"); do yaml2json $file | jq --arg transform.image publicintegrity/fec-loader:${IMAGE_TAG} | pachctl update-pipeline --no-port-forwarding; done
    when:
      event: deployment
      environment: production

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
