pipeline:
  install:
    image: node:10.15-alpine
    commands:
      - npm ci

  test:
    image: node:10.15-alpine
    commands:
      - npm test

  build_dry_run:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: publicintegrity/fec-loader
    cache_from: "publicintegrity/fec-loader:latest"
    tags:
      - ${DRONE_COMMIT_SHA:0:12}
      - latest
    dry_run: true
    when:
      event: [push, tag]

  build_push:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: publicintegrity/fec-loader
    cache_from: "publicintegrity/fec-loader:latest"
    tags:
      - ${DRONE_COMMIT_SHA:0:12}
      - latest
    when:
      event: deployment
      environment: production

  pipeline_update:
    image: "publicintegrity/pachctl:554b1a5ddfe3"
    environment:
      - PACHD_ADDRESS=pachd-api-grpc.pachyderm.svc.cluster.local:30650
      - IMAGE_NAME=publicintegrity/fec-loader
      - IMAGE_TAG=${DRONE_COMMIT_SHA:0:12}
    commands:
      - cat ./pipelines/*yml | yq write -d'*' - transform.image "$${IMAGE_NAME}:$${IMAGE_TAG}" | pachctl update pipeline
    when:
      event: deployment
      environment: production

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
