# Default values for node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: publicintegrity/fec-loader
  tag: latest
  pullPolicy: Always
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 100m
    memory: 512Mi
db:
  driver: postgres
  port: "5432"
