---
pipeline:
  name: fec-raw-rss-filing-check
transform:
  image: publicintegrity/fec-loader
  cmd:
  - bash
  stdin:
  - ./transforms/rss.sh /pfs/out/
parallelism_spec:
  constant: 1
input:
  cron:
    name: tick
    spec: "*/1 * * * *"
