---
pipeline:
  name: fec-raw-filing-download
transform:
  image: publicintegrity/fec-loader
  cmd:
  - bash
  stdin:
  - ./transforms/download.sh /pfs/check/ /pfs/out/
parallelism_spec:
  constant: 2
datum_tries: 2
input:
  pfs:
    name: check
    repo: fec-raw-rss-filing-check
    glob: /*
    empty_files: true
