---
pipeline:
  name: fec-raw-zips-download
transform:
  image: publicintegrity/fec-loader
  cmd:
  - bash
  stdin:
  - ./transforms/download-zips.sh /pfs/zips/ /pfs/out/
parallelism_spec:
  constant: 2
datum_tries: 2
input:
  pfs:
    name: zips
    repo: fec-raw-zip-filing-check
    glob: /*/*
    empty_files: true
