---
pipeline:
  name: fec-raw-load-filings
transform:
  image: publicintegrity/fec-loader:424040ab304e
  cmd:
  - bash
  stdin:
  - for file in $(find /pfs/filings/ -name "*.fec.gz"); do gunzip < $file | (echo "DELETE FROM fec_filings WHERE filing_id = $(echo $file | tr -dc '0-9');" && cat) | ./bin/fec2psql $(echo $file | tr -dc '0-9') | psql -v ON_ERROR_STOP=on --single-transaction 2> "/pfs/out/"$(echo $file | tr -dc '0-9')".log"; done
  secrets:
    - name: pachyderm-postgres-politics-auth
      env_var: PGHOST
      key: pghost
    - name: pachyderm-postgres-politics-auth
      env_var: PGDATABASE
      key: pgdatabase
    - name: pachyderm-postgres-politics-auth
      env_var: PGUSER
      key: pguser
    - name: pachyderm-postgres-politics-auth
      env_var: PGPASSWORD
      key: pgpassword
parallelism_spec:
  constant: 2
datum_tries: 2
input:
  pfs:
    name: filings
    repo: fec-raw-filing-download
    glob: /*
    lazy: true
