---
pipeline:
  name: fec-raw-load-filings
transform:
  image: publicintegrity/fec-loader
  cmd:
  - bash
  stdin:
  - ./transforms/load.sh /pfs/filings/ /pfs/out/
  secrets:
    - name: pachyderm-postgres-politics-auth
      env_var: PGHOST
      key: pghost
    - name: pachyderm-postgres-politics-auth
      env_var: PGDATABASE
      key: pgdatabase
    - name: pachyderm-postgres-politics-auth
      env_var: PGUSER
      key: pguser
    - name: pachyderm-postgres-politics-auth
      env_var: PGPASSWORD
      key: pgpassword
parallelism_spec:
  constant: 2
datum_tries: 2
input:
  union:
    - pfs:
        name: filings
        repo: fec-raw-filing-download
        glob: /*
        lazy: true
    - pfs:
        name: filings
        repo: fec-raw-filing-unzip
        glob: /*
        lazy: true
